routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth','IsAdmin'])->group(function(){
    Route::get('/management', 'HomeController@management')->name('management');
    Route::resource('tables','Table\TableController');
    Route::resource('category','Category\CategoryController')->middleware('auth');
    Route::resource('dishes','Dish\DishController')->middleware('auth');

});
Route::middleware(['auth','IsChef'])->group(function(){
    Route::view('/chefs', 'chef.index')->name('chef.all');
});
Route::middleware(['auth','IsServer'])->group(function(){
    Route::get('/servers', function () {
        return view('servers.index');
    })->name('servers');
    Route::resource('payments','Payment\PaymentController');
});


Route::get('/', function () {
    return view('home');
})->middleware('auth');


Auth::routes();





Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Table/TableController.php
<?php

namespace App\Http\Controllers\Table;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Table;
use App\Http\Requests\CreateTableRequest;
use App\Http\Requests\UpdateTableRequest;
use App\Http\Controllers\ApiController;

class TableController extends ApiController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //dd("AA");
        $tables = Table::all();
        return view('tables.index',compact("tables"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tables.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTableRequest $request)
    {
        Table::create( $request->all() + ['status'=> '1']);
        return redirect()->route('tables.index')->with('status', 'Table '.$request->name. " is save successfully");;

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Table $table)
    {
        return view('tables.edit',compact("table"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Table $table,UpdateTableRequest $request )
    {

        $table->update($request->all());
        return redirect()->route('tables.index')->with('status', 'Table '.$request->name. " is updated successfully");;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Table $table)
    {
        $name= $table->name;
        $table->delete();
        return redirect()->route('tables.index')->with('status', 'Table '. $name . " is deleted successfully");

    }

    public function jasontables()
    {
        $tables=Table::all();
        return $this->showall($tables);

    }
}

resources/views/tables/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center pt-5 pb-5" style="background-color: #fff">
        <div class="col-md-4">
            @include('inc.sidemenu')
        </div>
      <div class="col-md-8">
        <i class="fas fa-chair oranged-text"></i> Create a Table
        <hr>
        @if($errors->any())
        <div class="errormessage">
            @foreach ($errors->all() as $error)
                <div>{{ $error }}</div>
            @endforeach
        </div>
        @endif
        <form action="{{route('tables.store')}}" method="POST">
          @csrf
          <div class="form-group">
            <label for="tablename">Table Name</label>
            <input type="text" name="name" class="form-control"
             value="{{ old('name')}}">
          </div>
          <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
  </div>
@endsection
@section('JSscripts')
<script>
    $( document ).ready(function() {
    $("body").addClass('tablebg');
  });
</script>
@endsection

resources/views/tables/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            @include('inc.sidemenu')
        </div>
      <div class="col-md-8">
        <i class="fas fa-chair  oranged-text"></i> Edit Table
        <hr>
        @if($errors->any())
        <div class="errormessage">
            @foreach ($errors->all() as $error)
                <div>{{ $error }}</div>
            @endforeach
        </div>
        @endif
        <form action="{{route('tables.update',$table->id)}}" method="POST">
            @csrf
            @method("PUT")
          <div class="form-group">
            <label for="tableName">Table Name</label>
            <input type="text" name="name" class="form-control" value="{{ old('name',$table->name)}}">
          </div>
          <button type="submit" class="btn btn-primary">Update</button>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/tables/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center pt-5 pb-5" style="background-color: #fff">

        <div class="col-md-4">
            @include('inc.sidemenu')
        </div>

        <div class="col-md-8">
        <a type="button" class="btn btn-success" href="{{route('tables.create')}}">
            <i class="fas fa-plus-circle"></i>   Create New Table</a>
        <br/>
        <div class="row mt-5" style="width:70%">
          @foreach($tables as $table)
            <div class="col-sm-12 col-md-5 border-bottom">
                {{ Str::limit($table->name, 20) }}
            </div>
            <div class="col-sm-6 col-md-2 align-left border-bottom" >
                <a href="{{route('tables.edit',$table->id)}}" class="btn btn-warning btn-sm editbtn" >Edit</a>
            </div>
            <div class="col-sm-6 col-md-5  align-left border-bottom">
                <form action="{{route('tables.destroy',$table->id)}}" method="post">
                    @csrf
                    @method("DELETE")
                <div   class="btn btn-danger btn-sm tabledelete" style="color:#fff" tablename="{{$table->name}}">Delete</div>
                </form>

            </div>
            @endforeach
        </div>
    </div>
    </div>
  </div>

@endsection
@section('JSscripts')
<script>
    $( document ).ready(function() {

    $("body").addClass('tablebg');

    $('.tabledelete').click(function(){
         let tablename= $(this).attr('catname');
         let msg= `Are you sure you want to delete ${name}?`;
         let cm=confirm(msg);
         if(cm) $('form').submit();
    });

  });
</script>
@endsection