routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth','IsAdmin'])->group(function(){
    Route::get('/management', 'HomeController@management')->name('management');
    Route::resource('tables','Table\TableController');
    Route::resource('category','Category\CategoryController')->middleware('auth');
    Route::resource('dishes','Dish\DishController')->middleware('auth');

});
Route::middleware(['auth','IsChef'])->group(function(){
    Route::view('/chefs', 'chef.index')->name('chef.all');
});
Route::middleware(['auth','IsServer'])->group(function(){
    Route::get('/servers', function () {
        return view('servers.index');
    })->name('servers');
    Route::resource('payments','Payment\PaymentController');
});


Route::get('/', function () {
    return view('home');
})->middleware('auth');


Auth::routes();





Route::get('/home', 'HomeController@index')->name('home');

resources/views/inc/chef.blade.php
@if(Auth::user()->checkAdmin() || Auth::user()->checkChef())

 <div class="col-sm-3">
                            <a href="{{route('chef.all')}}">
                                <h4>Chef</h4>
                                <img width="50px" src="{{asset('img/chef.png')}}"/>
                            </a>
 </div>
 @endif
 

resources/views/inc/management.blade.php
 @if(Auth::user()->checkAdmin())
<div class="col-sm-3">
    <a href="{{route('management')}}">
        <h4>Managment</h4>
        <img width="50px" src="{{asset('img/food_manage_icon.png')}}"/>
    </a>
</div>
@endif

resources/views/inc/order.blade.php
@if(Auth::user()->checkAdmin() || Auth::user()->checkServer())
<div class="col-sm-3">
    <a href="{{route('servers')}}">
        <h4>Order</h4>
        <img width="50px" src="{{asset('img/food_serve.png')}}"/>
    </a>
</div>
@endif

resources/views/inc/pay.blade.php
@if(Auth::user()->checkAdmin() || Auth::user()->checkServer())
<div class="col-sm-3">
    <a href="{{route('payments.index')}}">
        <h4>Pay</h4>
        <img width="50px" src="{{asset('img/cashier_manage_icon.png')}}"/>
    </a>
</div>
@endif

resources/views/inc/sidemenu.blade.php
<div class="list-group">
    <a href="{{route('category.index')}}" class="list-group-item list-group-item-action"><i class="fas fa-align-justify orange-text"></i> Category</a>
    <a href="{{route('dishes.index')}}" class="list-group-item list-group-item-action"><i class="fas  fa-carrot orange-text"></i>&nbsp;Food</a>
    <a href="{{route('tables.index')}}" class="list-group-item list-group-item-action"><i class="fas fa-chair orange-text"></i> Table</a>
    <a href="{{route('register')}}" class="list-group-item list-group-item-action"><i class="fas fa-users-cog orange-text"></i> User</a>
</div>