routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth','IsAdmin'])->group(function(){
    Route::get('/management', 'HomeController@management')->name('management');
    Route::resource('tables','Table\TableController');
    Route::resource('category','Category\CategoryController')->middleware('auth');
    Route::resource('dishes','Dish\DishController')->middleware('auth');

});
Route::middleware(['auth','IsChef'])->group(function(){
    Route::view('/chefs', 'chef.index')->name('chef.all');
});
Route::middleware(['auth','IsServer'])->group(function(){
    Route::get('/servers', function () {
        return view('servers.index');
    })->name('servers');
    Route::resource('payments','Payment\PaymentController');
});


Route::get('/', function () {
    return view('home');
})->middleware('auth');


Auth::routes();





Route::get('/home', 'HomeController@index')->name('home');

app/Dish.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dish extends Model
{
    protected $fillable = ['name','price','image','description','category_id'];

    public function category(){
        return $this->belongsTo(Category::class);
    }

}

app/Http/Controllers/Dish/DishController.php
<?php

namespace App\Http\Controllers\Dish;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Dish;
use App\Category;
use App\Http\Requests\CreateDishRequest;
use App\Http\Requests\UpdateDishRequest;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\ApiController;


class DishController extends ApiController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dishes=Dish::all();
        $categories=Category::all();
        return view('dishes.index',compact("dishes","categories"));
    }

    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $dishes=Dish::all();
        $categories=Category::all();
        return view('dishes.create',compact("dishes","categories"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateDishRequest $request)
    {
       $data=$request->all();
       $filename=   uniqid("dish").$request->file('image')->getClientOriginalName();
       $data["image"]=$filename;
       $request->file('image')->storeAs('public/dish/',$filename);
        Dish::create($data);
        return redirect()->route('dishes.index')->with('status', $request->name. " is saved successfully");;
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dish=Dish::find($id);
        return $this->showOne($dish);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Dish $dish)
    {
        $categories=Category::all();
        return view('dishes.edit',compact("dish","categories"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Dish $dish,UpdateDishRequest $request)
    {

        $data=$request->all();

        if($request->hasFile('image')){

            $filename=   uniqid("dish").$request->file('image')->getClientOriginalName();
            $data["image"]=$filename;
            $request->file('image')->storeAs('public/dish/',$filename);
            //Storage::delete('dish/'.$dish->image);
            Storage::disk('dish')->delete($dish->image);
            $data['image']= $filename;
        }
        $dish->update($data);
        return redirect()->route('dishes.index')->with('status', $data['name']. " is updated successfully");;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dish $dish)
    {
        $name=$dish->name;
        Storage::disk('dish')->delete($dish->image);
        $dish->delete();
        return redirect()->route('dishes.index')->with('status', $name. " is delete successfully");;
    }

    public function jsondishes($category_id)
    {

        $dishes=Dish::where('category_id','=',$category_id)->get();
        return $this->showall($dishes);

    }
}

resources/views/dishes/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            @include('inc.sidemenu')
        </div>
      <div class="col-md-8" style="background-color: #fff">
        <i class="fas fa-carrot orange-text"></i>Create a Dish
        <hr>
        @if($errors->any())
        <div class="errormessage">
            @foreach ($errors->all() as $error)
                <div>{{ $error }}</div>
            @endforeach
        </div>
        @endif
        <form action="{{route('dishes.store')}}" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="form-group">
            <label for="menuName">Dish Name</label>
            <input type="text" name="name" class="form-control" placeholder="Menu...">
          </div>
          <div class="form-group">
            <label for="name">Price</label>
            <input type="text" name="price" class="form-control"  style="width:100px">
          </div>


                 <label for="MenuImage">Image</label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">Upload</span>
            </div>
            <div class="custom-file">
              <input type="file" name="image" class="custom-file-input" id="inputGroupFile01">
              <label class="custom-file-label" for="inputGroupFile01">Choose File</label>
            </div>
          </div>

          <div class="form-group">
            <label for="Description">Description</label>
            <textarea name="description" class="form-control">
            </textarea>
          </div>

          <div class="form-group">
            <label for="Category">Category</label>
            <select class="form-control" name="category_id">
                <option value="0">Select Category</option>
              @foreach ($categories as $category)
                <option value="{{$category->id}}">{{$category->name}}</option>

              @endforeach
            </select>
          </div>

          <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
  </div>
@endsection
@section('JSscripts')
<script>
    $( document ).ready(function() {
    $("body").addClass('dishbg');
  });
</script>
@endsection

resources/views/dishes/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center" >
        <div class="col-md-4">
            @include('inc.sidemenu')
        </div>
      <div class="col-md-8" style="background-color: #fff">
        <i class="fas fa-carrot orange-text"></i>Update a Dish
        <hr>
        @if($errors->any())
        <div class="errormessage">
            @foreach ($errors->all() as $error)
                <div>{{ $error }}</div>
            @endforeach
        </div>
        @endif
        <form action="{{route('dishes.update',$dish->id)}}" method="POST" enctype="multipart/form-data">
          @csrf
          @method("PUT")
          <div class="form-group">
            <label for="menuName">Dish Name</label>
            <input type="text" name="name" class="form-control" placeholder="Menu..." value="{{ old('name',$dish->name)}}">
          </div>
          <div class="form-group">
            <label for="name">Price</label>
            <input type="text" name="price" class="form-control"  style="width:100px" value="{{ old('price',$dish->price)}}">
          </div>


                 <label for="MenuImage">Image</label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">Upload</span>
            </div>
            <div class="custom-file">
              <input type="file" name="image" class="custom-file-input" id="inputGroupFile01">
              <label class="custom-file-label" for="inputGroupFile01">Choose File</label>
            </div>
          </div>

          <div class="form-group">
            <label for="Description">Description</label>
            <textarea name="description" class="form-control">
                {{ old('description',$dish->description)}}
            </textarea>
          </div>

          <div class="form-group">
            <label for="Category">Category</label>
            <select class="form-control" name="category_id">
                <option value="0">Select Category</option>
              @foreach ($categories as $category)
                <option value="{{$category->id}}" {{$dish->category_id === $category->id ? 'selected': ''}}>{{$category->name}}</option>

              @endforeach
            </select>
          </div>

          <button type="submit" class="btn btn-primary">Update</button>
        </form>
      </div>
    </div>
  </div>
@endsection
@section('JSscripts')
<script>
    $( document ).ready(function() {
    $("body").addClass('dishbg');
  });
</script>
@endsection

resources/views/dishes/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center pt-5 pb-5">
        <div class="col-md-4">
            @include('inc.sidemenu')
        </div>
      <div class="col-md-8 pt-5 pb-5" style="background-color: #fff">
        <i class="fas fa-carrot orange-text"></i>Dish
      <a href="{{route('dishes.create')}}" class="btn btn-success btn-sm float-right"><i class="fas fa-plus"></i> Create Dish</a>
        <hr>
        @if($errors->any())
        <div class="errormessage">
            @foreach ($errors->all() as $error)
                <div>{{ $error }}</div>
            @endforeach
        </div>
        @endif
        @foreach($dishes as $dish)
        <div class="row border-bottom" style="background-color: #fff">
            <div class="col-md-4">
                <img src="{{Storage::url('dish').'/'.$dish->image}}"  alt="{{$dish->name}}" width="100px" >
            </div>
            <div class="col-md-4">{{$dish->name}}</div>
            <div class="col-md-2">{{$dish->price}}</div>
            <div class="col-md-2">{{$dish->category->name}}</div>
            <div class="col-md-12">
                <button type="button" class="btn btn-link green-text" ><i class="far fa-eye"></i>View</button>
            <a class="btn btn-link oranged-text" href="{{route('dishes.edit',$dish->id)}}">
                    <i class="far fa-edit"></i>Update
                </a>
            <form action="{{route('dishes.destroy',$dish->id)}}" method="POST">
                <button type="button" class="btn btn-link red-text dishdelete"><i class="fas fa-trash-alt "
                    dishname="{{$dish->name}}"
                    ></i> Delete</button>
                    @csrf
                    @method("DELETE")

            </form>
            </div>

        </div>
        @endforeach





      </div>
    </div>
  </div>
@endsection
@section('JSscripts')
<script>
    $( document ).ready(function() {
    $("body").addClass('dishbg');
    $('.dishdelete').click(function(){
         let name= $(this).attr('dishname');
         let msg= `Are you sure you want to delete ${name}?`;
         let cm=confirm(msg);
         if(cm) $(this).parent().submit();
    });


  });
</script>
@endsection